# k8s/api-gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
