apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-flights-config
data:
  PORT: "50000"
  FLIGHT_SEARCH_SERVICE: "http://flight-search-service:50001"
  FLIGHT_BOOKING_SERVICE: "http://flight-booking-service:50002"
  NOTIFICATION_SERVICE: "http://notification-service:50003"
